[package]
name = "uuidgen7"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = false
opt-level = 3

[dependencies]
uuid = { version = "1.11.0", default-features = false, features = [
  "std",
  "v7",
] }
